In [12]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from pprint import pprint
from pathlib import Path
import numpy as np

# File location
combined = Path("Resources/combined_df.csv")

# Reading the data
combined_df = pd.read_csv(combined)

# display the first five rows of the df
df_2016.tail()

,Unnamed: 0,age,original_gender,gender,country,remote,num_employees,disorder_past,disorder_current,bring_up_phys_issue_in_interview,bring_up_mh_issue_in_interview,obs_exper_bad_resp_cur_prev,obs_of_other_inhibit_discuss_curr,comf_discuss_mh_disorder_cur_superv,willing_discuss_mh_issue_prev_superv,request_med_leave
1428,1428,34,Female,female,United States of America,Sometimes,No Response,No,No,No,No,Maybe/Not sure,No Response,No Response,Some of my previous employers,No Response
1429,1429,56,MALE,male,Afghanistan,Sometimes,No Response,No,No,Maybe,No,Maybe/Not sure,Maybe,No Response,No Response,No Response
1430,1430,52,Male,male,United States of America,Sometimes,100-500,Yes,Maybe,Maybe,No,"Yes, I observed",Yes,Yes,Some of my previous employers,Somewhat difficult
1431,1431,30,Female,female,United States of America,Sometimes,100-500,Maybe,Yes,Maybe,No,"Yes, I experienced",Maybe,Yes,"No, at none of my previous employers",Somewhat difficult
1432,1432,25,non-binary,other,Canada,Sometimes,100-500,Yes,Yes,Maybe,No,Maybe/Not sure,No,Maybe,No Response,Very difficult

In [6]:
combined_df.columns

Index(['Unnamed: 0', 'age', 'original_gender', 'gender', 'country',
       'num_employees', 'employer_discuss_mh', 'disorder_past',
       'disorder_current', 'bring_up_phys_issue_in_interview',
       'bring_up_mh_issue_in_interview', 'request_med_leave', 'age groups',
       'year', 'individual'],
      dtype='object')

In [11]:
combined_df["age groups"].count

<bound method Series.count of 0       35-44
1       25-34
2       35-44
3       35-44
4       35-44
        ...
2945    25-34
2946    45-54
2947    45-54
2948    25-34
2949    18-24
Name: age groups, Length: 2950, dtype: object>

In [10]:
combined_df["age groups"].age()

AttributeError: 'Series' object has no attribute 'age'

In [2]:
def analysis_func(col1, col2, a1, a2, a3, q1):
    sample_df = df_2016[[col1, col2]]
    sample_df

    a1_counts = sample_df[sample_df[col1] == a1][col2].value_counts()
    a2_counts = sample_df[sample_df[col1] == a2][col2].value_counts()
    a3_counts = sample_df[sample_df[col1] == a3][col2].value_counts()

    categories = sample_df[col2].unique()

    positions = np.arange(len(categories))

    plt.figure(figsize=(10, 6))
    bar_width = 0.2 
    plt.bar(positions, a1_counts, width=bar_width, label=a1, align='center')
    plt.bar(positions + bar_width, a2_counts, width=bar_width, label=a2, align='center')
    plt.bar(positions + 2 * bar_width, a3_counts, width=bar_width, label=a3, align='center')

    plt.xticks(positions + bar_width, categories)

    # plt.xlabel('Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?')
    # plt.ylabel('Count')
    plt.title(q1)
    plt.legend()
    plt.legend(title='Do you work remote?')
    plt.savefig(f'Figures/{col1}_{col2}.png')
    plt.show()